name: Unikernels
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build relay
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.relay
      -
        name: Build submission
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.submission
      -
        name: Build signer
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.signer
      -
        name: Build spamfilter
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.spamfilter
      -
        name: Build verifier
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.verifier
